* Using R with Emacs and ESS - A Multi-functional Environment
This Org file explains the Emacs configuration to write code in the R langues in Emacs. For more information go to [[http://lucidmanager.org/using-r-with-emacs/][The Devil is in the Data]].

This org file shows the elisp code for a minimal configuration to write R code in Emacs. You can write all relevant code to an init file ([[https://orgmode.org/manual/Extracting-source-code.html][tangle]]) with the =C-c C-v C-t= keystrokes.

** Installing packages
#+PROPERTY: header-args :tangle yes :tangle init.el :results silent
This first snippet adds the Melpa repository and installs the required packages, but it is not saved to the init file as we only need to execute this once. Press =C-c C-c= to evaluate this code block. ESS will ask confirmation to run the code.

#+BEGIN_SRC emacs-lisp header-args :tangle no
; Configure repository
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
; list the packages
(setq package-list
    '(ess ess-smart-underscore org-ref auto-complete))

; activate all the packages
(package-initialize)

; fetch the list of packages available 
(unless package-archive-contents
  (package-refresh-contents))

; install the missing packages
(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))
#+END_SRC

* Configure ESS
[[https://ess.r-project.org/][Emacs Speaks Statistics]] (ESS) supports editing of scripts and interaction with various statistical analysis programs such as R. You also need to install the R software. You can start an R terminal with =M-x R= and enter the preferred working directory.

In ESS, the underscore key is mapped to the =<-= assignment operator in R. If you need an underscore, you need to type it twice. This functionality can be annoying when you are an avid user of ggplot. The [[https://github.com/mattfidler/ess-smart-underscore.el][ess-smart-underscore]] package solves this issue by allowing a single underscore in certain circumstances.

#+BEGIN_SRC emacs-lisp
(require 'ess-site)
(require 'ess-smart-underscore)
#+END_SRC

* Org Babel
Org Babel is the enables literate programming, including the functionality in this file.

#+BEGIN_SRC emacs-lisp
;; Active the R language in Babel
(org-babel-do-load-languages
 'org-babel-load-languages
 '((R . t)))
#+END_SRC

* Auto complete
#+BEGIN_SRC emacs-lisp
;; Auto complete
(require 'auto-complete-config)
(ac-config-default)
#+END_SRC

* Org LaTeX and BibTeX
#+BEGIN_SRC emacs-lisp
;;Org BibTeX references
(require 'org-ref)
(org-ref-define-citation-link "citeA" ?a)
(setq org-latex-pdf-process
      '("pdflatex -interaction nonstopmode -output-directory %o %f"
	"bibtex %b"
	"pdflatex -interaction nonstopmode -output-directory %o %f"
	))

;; Org Mode Latex Templates
(require 'ox-latex)

;; American Psychological Association papers
(add-to-list 'org-latex-classes '("apa6"
    "\\documentclass[a4paper, jou]{apa6}
     [NO-DEFAULT-PACKAGES]
     \\usepackage[hidelinks]{hyperref}
     \\usepackage{apacite}
     \\usepackage[british]{babel}
     \\usepackage{ccicons}"
	       ("\\section{%s}" . "\\section*{%s}")
	       ("\\subsection{%s}" . "\\subsection*{%Rs}")
	       ))
#+END_SRC
