#+TITLE: Emacs Configuration Generation File
#+AUTHOR: Peter Prevos
#+PROPERTY: header-args :tangle yes :tangle ~/.emacs.d/init.el

* Introduction
Emacs needs an [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html][Init File]] to store all configurations. This file uses literate programming principles to document and define the configuration.

To create the init file in the =.emacs.d= folder, execute =C-c C-v C-t= (=org-babel-tangle=). 

The next time you start Emacs it will be loaded. If you don't want to restart Emacs, then type =C-c C-v C-b= to evaluate all blocks. You can also evaluate each code block individually with =C-c C-c= or each line with =C-x X-e=.

Emacs will ask you to confirm that you want to execute code. To stop Emacs asking for confirmation run =(setq org-confirm-babel-evaluate nil)=.

** Credits
This configuration is based on [[https://github.com/larstvei/dot-emacs][larstvei/dot-emacs]].

* Basic Configuration
** TODO Visual elements
This snippet changes the overall look-and-feel of Emacs.

#+BEGIN_SRC emacs-lisp
;; This init file is generated with an Org-Mode file. 
;; Any manual changes will be overwritten by the script.
;; -----------------------------------------------------

;; Visual enhancements
;; Hide toolbar
(tool-bar-mode -1)
#+END_SRC
   
** Editing configuration
This snippet
- [[https://www.gnu.org/software/emacs/manual/html_node/emacs/CUA-Bindings.html][CUA mode]] (Common User Acess) to enable =C-c= for copy, =C-v= for paste, and so on.
- [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Visual-Line-Mode.html][Visual Line Mode]] wraps long lines near the window edge.

#+BEGIN_SRC emacs-lisp
;; Editing configuration

;; Common User Access
(cua-mode t)
;; Line wrapping
(global-visual-line-mode t)
#+END_SRC



