#+title: Preface
:NOTES:
- [X] Personal experience with productivity and Emacs
- [X] Who is this book for?
- [X] "Emacs is [[https://www.youtube.com/watch?v=XRpHIa-2XCE][Willy Wonka's chocolate factory]] for writing text"
:END:

My writing journey started in the early 1990s with paper diaries to record my random thoughts and as a travel diary. Paper notebooks are great, and I still use them today as the primary place to gather thoughts. The only disadvantage of paper notebooks is finding old information and linking bits and pieces together takes a lot of work. Besides my notebooks, I also amassed a paper archive, a library and a collection of photographs. Being a computing enthusiast, I have ever since searched for the ultimate digital tool to combine all these pieces of information into the ultimate personal knowledge management system.

Over the years, I have tried a multitude of computer applications to achieve this ideal state. I wanted something that stores information in an enduring format that does not rely on a brand of software. Ideally, it had to be searchable and a single application to undertake different tasks. 

I used to hop from application to application, jump from the action list to my schedule, and move on to the word processor, spreadsheet, PDF reader, etc. I managed a complex web of software tools to deliver a single project. Wouldn't it be nice if there was one program that could help you with all your tasks?

My online research always pointed towards Emacs. I tried to use it in the early 2000s but quickly gave up due to the steep learning curve. About ten years ago, I tried again, and this time, I was helped by a steady flow of websites and instructional videos to get me started. Over the following years, I studied Emacs and configured it to write and publish articles and books.

Emacs is to me like being in Willy Wonka's Chocolate Factory where almost everything is possible. I crafted EWS to meet my specific needs for writing this book and other projects, which I am are also useful for other authors.

My commitment to crafting the Emacs Writing Studio (EWS) configuration was driven by a desire to share the benefits of my journey with others. EWS is not just a tool, but a culmination of years of learning and experimentation. My aim was to write the book that I would have loved to read when I first came in contact with Emacs.

This book, which is both a guide to EWS and a product of its capabilities, has been rigorously tested and refined to ensure it meets the needs of large writing projects.  

* Acknowledgements
The development and maintenance of a complex system like Emacs is a testament to the power of community. I am deeply grateful to the countless volunteers who have contributed to its core system's code and the abundance of packages. Their collective effort is what makes Emacs a thriving ecosystem.

My motivation for writing this book came from the inspiring work of people like Protesilaos (Prot) Stavrou, David Wilson from /System Crafters/ and many others who helped me flatten the learning curve of my Emacs journey through their blogs and YouTube videos.
 
Mastodon and Emacs users Harold Kirsch, Thomas Montfort, Ben Finney, Antonio Simón (Quijote Libre), Bob Irving,  Frédéric Vachon, and Erin Stearns have reviewed early versions of the book. Their feedback has helped to make this book both easier to read and more comprehensive, which is a fine balance to achieve.

Thanks to Stefan Kangas and Fredrik Salomonsson for picking up some typos in the text.

#+begin_export html
&nbsp;
<p style="text-align:right">Peter Prevos</p>
#+end_export
#+begin_export latex
\vspace{1em}
\begin{flushright}
Peter Prevos
\end{flushright}
#+end_export
